#!/usr/bin/env bash
# Builds libonnxruntime_providers_hip.so - the HIPExecutionProvider for ONNX Runtime.
#
# Usage: ./build.sh [ort_source_dir]
#   ort_source_dir defaults to /tmp/opencode/ort (onnxruntime v1.27.1).
set -euo pipefail

SRC_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ORT_SRC="${1:-/tmp/opencode/ort}"
BUILD_DIR="${SRC_DIR}/build"
HIPCC="${HIPCC:-hipcc}"

mkdir -p "${BUILD_DIR}"

echo "[build] ONNX Runtime source: ${ORT_SRC}"

# ---------------------------------------------------------------------------
# 1. Resolve the onnxruntime external header dependencies.
# ---------------------------------------------------------------------------
DEPS_DIR="${BUILD_DIR}/deps"
mkdir -p "${DEPS_DIR}"

fetch() {  # $1=url $2=dest_dir_name
  local url="$1" dest="$2"
  if [ ! -d "${DEPS_DIR}/${dest}" ]; then
    echo "[build] downloading ${dest} ..."
    curl -sL "$url" -o "${BUILD_DIR}/_dep.zip"
    mkdir -p "${DEPS_DIR}/${dest}"
    unzip -q -o "${BUILD_DIR}/_dep.zip" -d "${DEPS_DIR}/${dest}"
  fi
}

# Microsoft GSL (header only). v4.2.1 is what onnxruntime v1.27.1 pins.
if [ ! -d "${DEPS_DIR}/gsl" ]; then
  fetch "https://github.com/microsoft/GSL/archive/refs/tags/v4.2.1.zip" gsl
fi
# SafeInt (header only). v3.0.28.
if [ ! -d "${DEPS_DIR}/safeint" ]; then
  fetch "https://github.com/dcleblanc/SafeInt/archive/refs/tags/3.0.28.zip" safeint
fi

GSL_INC="$(find "${DEPS_DIR}/gsl" -maxdepth 2 -type d -name include | head -1)"
SAFEINT_INC="$(find "${DEPS_DIR}/safeint" -maxdepth 2 -name "SafeInt.hpp" -printf '%h\n' | head -1)"

# onnxruntime_config.h is normally generated by cmake; produce a minimal copy.
if [ ! -f "${BUILD_DIR}/inc/onnxruntime_config.h" ]; then
  mkdir -p "${BUILD_DIR}/inc"
  printf '#pragma once\n#define ORT_BUILD_INFO "hip-provider"\n#define ORT_VERSION "1.27.1"\n' > "${BUILD_DIR}/inc/onnxruntime_config.h"
fi

# ---------------------------------------------------------------------------
# 2. Compile the provider sources (hipcc for device code in hip_graph.cc).
# ---------------------------------------------------------------------------
CXXFLAGS="-std=c++17 -O3 -fPIC -fvisibility=hidden -w"
COMMON_DEFS="-DONNX_ML=1 -DONNX_NAMESPACE=onnx -DDISABLE_CONTRIB_OPS"

INC_FLAGS=" \
  -I${BUILD_DIR} \
  -I${BUILD_DIR}/inc \
  -I${ORT_SRC}/include \
  -I${ORT_SRC}/include/onnxruntime \
  -I${ORT_SRC}/onnxruntime \
  -I${GSL_INC} \
  -I${SAFEINT_INC} \
  -I/usr/include/eigen3 \
  -I/usr/include \
"

OBJ_DIR="${BUILD_DIR}/obj"
mkdir -p "${OBJ_DIR}"

GXX="g++"
# Compile the ORT bridge + factory with g++ (no device code).
"${GXX}" ${CXXFLAGS} ${COMMON_DEFS} ${INC_FLAGS} -c "${ORT_SRC}/onnxruntime/core/providers/shared_library/provider_bridge_provider.cc" -o "${OBJ_DIR}/provider_bridge_provider.o"
"${GXX}" ${CXXFLAGS} ${COMMON_DEFS} ${INC_FLAGS} -c "${ORT_SRC}/onnxruntime/core/providers/shared_library/provider_ort_api_init.cc" -o "${OBJ_DIR}/provider_ort_api_init.o"
"${GXX}" ${CXXFLAGS} ${COMMON_DEFS} ${INC_FLAGS} -c "${SRC_DIR}/hip_execution_provider.cc" -o "${OBJ_DIR}/hip_execution_provider.o"
"${GXX}" ${CXXFLAGS} ${COMMON_DEFS} ${INC_FLAGS} -c "${SRC_DIR}/hip_provider_factory.cc" -o "${OBJ_DIR}/hip_provider_factory.o"

# hip_graph.cc contains the device kernels (via hip_kernels.h): compile + link
# with hipcc so the device code is embedded in the shared library.
"${HIPCC}" --offload-arch=gfx1100 ${CXXFLAGS} ${COMMON_DEFS} ${INC_FLAGS} \
  -c "${SRC_DIR}/hip_graph.cc" -o "${OBJ_DIR}/hip_graph.o"
echo "[build] compiled hip_graph.o (hipcc, gfx1100)"

# ---------------------------------------------------------------------------
# 3. Link the provider shared library.
# ---------------------------------------------------------------------------
"${HIPCC}" --offload-arch=gfx1100 -shared \
  "${OBJ_DIR}/provider_bridge_provider.o" \
  "${OBJ_DIR}/provider_ort_api_init.o" \
  "${OBJ_DIR}/hip_execution_provider.o" \
  "${OBJ_DIR}/hip_provider_factory.o" \
  "${OBJ_DIR}/hip_graph.o" \
  -o "${BUILD_DIR}/libonnxruntime_providers_hip.so" \
  -lpthread -ldl

echo "[build] done: ${BUILD_DIR}/libonnxruntime_providers_hip.so"
